site_name: iscc-core

theme:
  name: material
  features:
    - navigation.indexes
#    - navigation.sections
#    - navigation.expand

plugins:
  - search
  - autorefs
  - mkdocstrings:
      watch:
        - iscc_core
      handlers:
        python:
          selection:
            docstring_style: restructured-text
          rendering:
            show_root_heading: false
            show_root_toc_entry: true
            show_root_full_path: true
            show_object_full_path: false
            show_root_members_full_path: false
            show_category_heading: true
            show_if_no_docstring: true
            show_signature_annotations: true
            show_source: true
            show_bases: true
            group_by_category: true
            heading_level: 3
            members_order: source

markdown_extensions:
  - admonition
  - pymdownx.highlight
  - pymdownx.superfences

nav:
  - ISCC-CORE Reference: index.md
  - Components:
    - components/index.md
    - Meta-Code: components/code_meta.md
    - Content-Code:
      - components/content/index.md
      - Text: components/content/code_content_text.md
      - Image: components/content/code_content_image.md
      - Audio: components/content/code_content_audio.md
      - Video: components/content/code_content_video.md
    - Data-Code: components/code_data.md
    - Instance-Code: components/code_instance.md
  - Algorithms:
    - CDC: algorithms/cdc.md
    - Simhash: algorithms/simhash.md
    - Minhash: algorithms/minhash.md
    - WTAHash: algorithms/wtahash.md
  - Codec: codec/codec.md
  - Utilities: utilities/utils.md
