site_name: iscc-core

theme:
  name: material

plugins:
  - search
  - mkdocstrings:
      default_handle: python
      watch:
        - iscc_core
      handlers:
        python:
          selection:
            docstring_style: restructured-text
          rendering:
            show_source: true
            show_object_full_path: false
            members_order: source

markdown_extensions:
  - admonition
  - pymdownx.highlight
  - pymdownx.superfences

nav:
  - Home: index.md
  - ISCC-CORE Reference:
      - Components:
          - Meta-Code: code_meta.md
          - Content-Code:
            - Text: code_text.md
            - Image: code_image.md
            - Audio: code_audio.md
            - Video: code_video.md
          - Data-Code: code_data.md
          - Instance-Code: code_instance.md
      - Algorithms:
        - CDC: cdc.md
        - Simhash: simhash.md
        - Minhash: minhash.md
        - WTAHash: wtahash.md
      - Codec: codec.md
      - Utilities: utils.md
