site_name: "ISCC - Codec & Algorithms"
site_description: 'International Standard Content Code - Core algorithms python implementation.'
site_author: 'Titusz Pan'
site_url: 'https://core.iscc.codes'

# Repository
repo_name: 'iscc/iscc-core'
repo_url: 'https://github.com/iscc/iscc-core'
edit_uri: 'edit/main/docs/'

# Copyright
copyright: 'Copyright © 2016-2021 The Authors
| <a href="https://iscc.foundation/privacy">Privacy Policy</a>
| <a href="https://iscc.foundation/cookies">Cookie Policy</a>
| <a href="https://iscc.foundation/imprint">Imprint</a>
| <a href="https://iscc.foundation/disclaimer">Disclaimer</a>'

extra_css:
  - stylesheets/extra.css

extra:
  analytics:
    provider: custom

theme:
  name: material
  custom_dir: overrides
  logo: images/iscc-logo-icon-white.svg
  favicon: images/iscc-logo-icon-black.svg
  language: en
  font:
    text: Readex Pro
    code: JetBrains Mono
  palette:
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
  features:
    - toc.integrate
    - navigation.indexes
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.expand


plugins:
  - search
  - autorefs
  - mkdocstrings:
      watch:
        - iscc_core
      handlers:
        python:
          selection:
            docstring_style: restructured-text
          rendering:
            show_root_heading: false
            show_root_toc_entry: false
            show_root_full_path: true
            show_object_full_path: false
            show_root_members_full_path: false
            show_category_heading: false
            show_if_no_docstring: false
            show_signature_annotations: true
            show_source: false
            show_bases: false
            group_by_category: false
            heading_level: 2
            members_order: source


markdown_extensions:
  - meta
  - admonition
  - pymdownx.details
  - abbr
  - attr_list
  - md_in_html
  - footnotes
  - toc:
      permalink: "#"
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

nav:
  - Overview: index.md
  - Types: constants.md
  - Codec: codec/codec.md
  - ISCC-CODE: iscc_code.md
  - ISCC-ID: iscc_id.md
  - Components:
    - components/index.md
    - Meta-Code: components/code_meta.md
    - Content-Codes:
      - components/content/index.md
      - Text-Code: components/content/code_content_text.md
      - Image-Code: components/content/code_content_image.md
      - Audio-Code: components/content/code_content_audio.md
      - Video-Code: components/content/code_content_video.md
      - Mixed-Code: components/content/code_content_mixed.md
    - Data-Code: components/code_data.md
    - Instance-Code: components/code_instance.md
  - Algorithms:
    - CDC: algorithms/cdc.md
    - DCT: algorithms/dct.md
    - Simhash: algorithms/simhash.md
    - Minhash: algorithms/minhash.md
    - WTAHash: algorithms/wtahash.md
  - Options: options/options.md
  - Utilities: utilities/utils.md
  - Conformance: conformance.md
