site_name: "ISCC - Core Algorithms"
site_description: 'International Standard Content Code - Core algorithms python implementation.'
site_author: 'Titusz Pan'
site_url: 'http://iscc.codes'

# Repository
repo_name: 'iscc/iscc-core'
repo_url: 'https://github.com/iscc/iscc-core'
edit_uri: 'edit/main/docs/'

# Copyright
copyright: 'Copyright © 2016-2021 The Authors
| <a href="https://iscc.foundation/privacy">Privacy Policy</a>
| <a href="https://iscc.foundation/cookies">Cookie Policy</a>
| <a href="https://iscc.foundation/imprint">Imprint</a>
| <a href="https://iscc.foundation/disclaimer">Disclaimer</a>'

theme:
  name: material
  language: en
  palette:
    primary: 'blue'
    accent: 'pink'
  features:
    - navigation.indexes
#    - navigation.sections
#    - navigation.expand

plugins:
  - search
  - autorefs
  - mkdocstrings:
      watch:
        - iscc_core
      handlers:
        python:
          selection:
            docstring_style: restructured-text
          rendering:
            show_root_heading: false
            show_root_toc_entry: true
            show_root_full_path: true
            show_object_full_path: false
            show_root_members_full_path: false
            show_category_heading: true
            show_if_no_docstring: false
            show_signature_annotations: true
            show_source: false
            show_bases: true
            group_by_category: true
            heading_level: 3
            members_order: source

markdown_extensions:
  - admonition
  - pymdownx.highlight
  - pymdownx.superfences

nav:
  - Overview: index.md
  - ISCC-CODE: iscc_code.md
  - ISCC-ID: iscc_id.md
  - Components:
    - components/index.md
    - Meta-Code: components/code_meta.md
    - Content-Code:
      - components/content/index.md
      - Text: components/content/code_content_text.md
      - Image: components/content/code_content_image.md
      - Audio: components/content/code_content_audio.md
      - Video: components/content/code_content_video.md
      - Mixed: components/content/code_content_mixed.md
    - Data-Code: components/code_data.md
    - Instance-Code: components/code_instance.md
  - Algorithms:
    - CDC: algorithms/cdc.md
    - DCT: algorithms/dct.md
    - Simhash: algorithms/simhash.md
    - Minhash: algorithms/minhash.md
    - WTAHash: algorithms/wtahash.md
  - Schema: schema/schema.md
  - Codec: codec/codec.md
  - Options: options/options.md
  - Utilities: utilities/utils.md
