[tool.poetry]
name = "iscc-core"
version = "0.1.0"
description = "ISCC: Reference Implementation of standardized core algorithms."
authors = ["Titusz <tp@py7.de>"]
license="BSD 3-clause"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.6"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
